[package]
name = "oxc_react_compiler_ssa"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
oxc_react_compiler_diagnostics = { workspace = true }
oxc_react_compiler_hir = { workspace = true }
oxc_react_compiler_lowering = { workspace = true }
indexmap = "2"
